POST http://137.204.57.93:7739/harvester/simulation
Content-Type: application/json

{
	"devId": "GasSensor",
	"harvId": "SolarLightLoad",

	"lowpwrI": 1,
	"activeI": 20,
	"duty": 20,
	"Vload": 3.3,
  "devAvgI": null,
	"batSOC": null,
	"batV": 3.82,

	"phIrr": 700,
	"thThot": null,
	"thTcold": null,
	"thGrad": null,
	"vibAcc": null,
	"vibFreq": null
}

#####
GET  http://137.204.57.93:7739/harvester/simulation/ceecfd53-6fbb-432b-a366-d4e2031907f1

#####
GET  http://137.204.57.93:7739/harvester/simulation/eb20a801-85e4-4445-8a5d-88a510b80be1
####
{
  "terminated": true,
  "result": {
    "devId": "GasSensor",
    "harvId": "SolarLightLoad",
    "batState": 0,
    "batlifeh": 98.036,
    "simStatus": 1,
    "date": "05-Apr-2022 20:08:47",
    "tChargeh": -1.0,
    "dSOCrate": -0.938
  }
}

### create DrHarvester arrowhead service
POST http://137.204.57.93:8443/serviceregistry/register
Content-Type: application/json

{
   "endOfValidity":"2031-01-01 23:59:59",
   "interfaces":[
      "HTTPS-SECURE-JSON"
   ],
   "providerSystem":{
      "address":"http://137.204.57.93",
      "port": 7739,
      "systemName":"dr-harvester"
   },
   "secure":"NOT_SECURE",
   "serviceDefinition":"dr-harvester",
   "serviceUri":"harvester",
   "version":0
}
####
GET http://137.204.57.93:8443/serviceregistry/mgmt/2091

###
DELETE http://137.204.57.93:8443/serviceregistry/mgmt/3061
Accept: application/json
https://iotime-2022.github.io/

### create Emeritus Harvester arrowhead service
POST http://137.204.57.93:8443/serviceregistry/register
Content-Type: application/json

{
   "endOfValidity":"2031-01-01 23:59:59",
   "interfaces":[
      "HTTPS-SECURE-JSON"
   ],
   "providerSystem":{
      "address":"http://localhost",
      "port": 2022,
      "systemName":"emeritus-harvester"
   },
   "secure":"NOT_SECURE",
   "serviceDefinition":"emeritus-harvester",
   "serviceUri":"harvester",
   "version":0
}
####
### create Emeritus Harvester arrowhead service
POST http://137.204.57.93:8443/serviceregistry/register
Content-Type: application/json

{
   "endOfValidity":"2031-01-01 23:59:59",
   "interfaces":[
      "HTTPS-SECURE-JSON"
   ],
   "providerSystem":{
      "address":"http://137.204.57.93",
      "port": 4308,
      "systemName":"GasSensor"
   },
   "secure":"NOT_SECURE",
   "serviceDefinition":"GasSensor",
   "serviceUri":"gas-sensor-harvester-info",
   "version":0
}


### create Emeritus Harvester arrowhead service
POST http://137.204.57.93:8443/serviceregistry/register
Content-Type: application/json

{
   "endOfValidity":"2031-01-01 23:59:59",
   "interfaces":[
      "HTTPS-SECURE-JSON"
   ],
   "providerSystem":{
      "address":"http://3b1e-93-34-112-8.ngrok.io",
      "port": 80,
      "systemName":"thingshub"
   },
   "secure":"NOT_SECURE",
   "serviceDefinition":"thingshub",
   "serviceUri":"status",
   "version":0
}

### create remote Emeritus Harvester arrowhead service
POST http://137.204.57.93:8443/serviceregistry/register
Content-Type: application/json

{
   "endOfValidity":"2031-01-01 23:59:59",
   "interfaces":[
      "HTTPS-SECURE-JSON"
   ],
   "providerSystem":{
      "address":"http://137.204.143.89",
      "port": 2022,
      "systemName":"emeritus-harvester-remote"
   },
   "secure":"NOT_SECURE",
   "serviceDefinition":"emeritus-harvester",
   "serviceUri":"harvester",
   "version":0
}

#### 489
DELETE http://137.204.57.93:8443/serviceregistry/mgmt/systems/900
Accept: application/json


### create remote Emeritus Harvester arrowhead service
POST http://192.168.1.5:8443/serviceregistry/register
Content-Type: application/json

{
   "endOfValidity":"2031-01-01T23:59:59+01:00",
   "interfaces":[
      "HTTPS-SECURE-JSON"
   ],
   "providerSystem":{
      "address":"137.204.40.174",
      "port": 3001,
      "systemName":"test"
   },
   "secure":"NOT_SECURE",
   "serviceDefinition":"test",
   "serviceUri":"status",
   "version":0
}
### create remote Emeritus Harvester arrowhead service
POST http://137.204.57.93:8443/serviceregistry/register
Content-Type: application/json

{
   "endOfValidity":"2031-01-01 23:59:59",
   "interfaces":[
      "HTTPS-SECURE-JSON"
   ],
   "providerSystem":{
      "address":"http://ed25-2001-b07-644f-3494-e4dc-e422-decf-c522.ngrok.io",
      "port": 80,
      "systemName":"thingshublolo"
   },
   "secure":"NOT_SECURE",
   "serviceDefinition":"thingshublolo",
   "serviceUri":"status",
   "version":0
}


### create remote Emeritus Harvester arrowhead service
POST http://192.168.1.5:8443/serviceregistry/register
Content-Type: application/json

{
   "endOfValidity":"2031-01-01T23:59:59+01:00",
   "interfaces":[
      "HTTPS-SECURE-JSON"
   ],
   "providerSystem":{
      "address":"192.168.1.9",
      "port": 3001,
      "systemName":"thingshub"
   },
   "secure":"NOT_SECURE",
   "serviceDefinition":"thingshub",
   "serviceUri":"status",
   "version":0
}


### create Emeritus Harvester arrowhead service
POST http://192.168.1.5:8443/serviceregistry/register
Content-Type: application/json

{
   "endOfValidity":"2031-01-01T23:59:59+01:00",
   "interfaces":[
      "HTTPS-SECURE-JSON"
   ],
   "providerSystem":{
      "address":"localhost",
      "port": 2022,
      "systemName":"emeritus-harvester"
   },
   "secure":"NOT_SECURE",
   "serviceDefinition":"emeritus-harvester",
   "serviceUri":"harvester",
   "version":0
}

### create Emeritus Harvester arrowhead service
POST http://192.168.1.5:8443/serviceregistry/register
Content-Type: application/json

{
   "endOfValidity":"2031-01-01T23:59:59+01:00",
   "interfaces":[
      "HTTPS-SECURE-JSON"
   ],
   "providerSystem":{
      "address":"192.168.1.5",
      "port": 4308,
      "systemName":"GasSensor"
   },
   "secure":"NOT_SECURE",
   "serviceDefinition":"GasSensor",
   "serviceUri":"gas-sensor-harvester-info",
   "version":0
}
